name: Push
on:
  push:
    branches: master
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install bazelisk
        run: curl -L "https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64" | install -D /dev/stdin "${GITHUB_WORKSPACE}/bin/bazel"
      - uses: azure/docker-login@v1
        with:
          username: uhthomas
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: bazel run //cmd/kipp:push
